version: '2'
services:
  node:
    build: ./
    restart: always
    container_name: library_backend
    volumes:
      - ./lib:/app/lib
      - ./migrations:/app/migrations
    ports:
      - "4000:4000"
